### ISSUE TITLE
Update data w.r.t the latest changes

### ISSUE THREAD

**Issue by sahilnanda1995** [buidl-labs/yieldscan-backend-ts#19]
# TODO

## 🎯 &nbsp; What is the problem that needs to be solved?

- [x] History(eraPoints, rewards, slashing Info) update w.r.t the era change
- [x] active validators w.r.t the session change
- [ ] checks regarding these updates
## ⏳ &nbsp; ETA

~By `29th June, 2020 - EOD`~ **Missed**

New ETA: To be updated

**Comment by saumyakaran** [comment]
@sahilnanda1995 I've deprioritized this for now, shifting to Icebox on zenhub - validator profile key stats endpoints and authentication + editing off-chain info is top priority
