### ISSUE TITLE
Provide API endpoint for validator profile

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-backend-ts#25]
# TODO

## 🎯 &nbsp; What is the problem that needs to be solved?

Using the [profile specs doc](https://www.notion.so/saumyakaran/Profile-specs-21b7bb06dc804047b578680ac10cfb25), provide API endpoints for the activity feed, key stats, linked validators, etc. on validators profile.

### 🗒 &nbsp; Summary
A brief overview of the problem to be solved. Include all relevant data points.

### ✅ &nbsp; Outcomes

- [x] Key stats data display
- [x] Contact info and social links endpoint (via identity module)

**Good to have** [+P3]

- [ ] Change in stake amount - Nominator or validator staked or unstaked `x` amount
Activity feed with the following info:
- [ ] History of slashes (red alert) ✅
- [ ] History of reward claims for the validator (triggered by anyone) - Era indexes for claimed rewards with timestamps

## ⏳ &nbsp; ETA

To be updated

**Comment by saumyakaran** [comment]
@sahilnanda1995 Updated the outcomes - shifted activity feed to "good to have [+p3]" section.

Based on this new info, could you please update the ETA for this?
