### ISSUE TITLE
sprint/m2-shipment

### ISSUE THREAD

**Issue by sahilnanda1995** [buidl-labs/yieldscan-backend-ts#36]
# TODO

### ✅ &nbsp; Outcomes
- [x] replace "get all stashes(`api.derive.staking.stashes()`)" with "get all account Id's(`api.query.system.account.keys()`)"
- [x] add waiting validators in crawlers
- [x] map nominators to waiting validators
- [x] #24 
- [x] #33 
- [x] #19 
- [x] add check for current era/session. Also, return error message informing updating new data
- [ ] separate the api and crawlers for better performance

## ⏳ &nbsp; ETA
To be updated.

**Comment by sahilnanda1995** [comment]
moved _"separate the api and crawlers"_ to a new issue here #47
