### ISSUE TITLE
[M2] - Backend status tracker

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-backend-ts#7]
### Data endpoints
- [ ] Validator info (like risk score, pool reward, stakes, commission, address, number of nominators and identity)
- [ ] Suggested set of validators for selected risk level

## Dashboard overview
- [ ] History of earnings for selected nominator (stashId)
- [ ] Expected earnings based on current selections
- [ ] Prompts to update nominations if they aren't earning the optimal returns for my selected risk and reward preference
- [ ] Unclaimed rewards info

### Validators
- [ ] TODO

### Nominators
- [ ] TODO

### Council members
- [ ] TODO

cc @sahilnanda1995 Please feel free to edit this as you see fit
